# numpy
#### NumPy is an open-source Python library used for numerical computing. It provides the ndarray, a homogeneous, multi-dimensional array that is more memory-efficient and faster than Python lists. NumPy also offers built-in functions for mathematical operations, linear algebra, statistics, random number generation, and array manipulation. It is widely used in data science, machine learning, deep learning, and scientific computing.

#### At the core of numpy package is th ndimentional array object.

# why numpy?

#### 1. Speed: Operations on large arrays are much faster than using Python lists because NumPy is implemented largely in C.
#### 2. Arrays: It provides the ndarray object, which stores homogeneous data efficiently.
#### 3. Mathematics: Supports vectorized operations, linear algebra, statistics, Fourier transforms, and more.
#### 4. Memory efficiency: Uses less memory than equivalent Python data structures.
#### 5. Scientific ecosystem: Libraries like Pandas, SciPy, and TensorFlow build on NumPy arrays.



# difference b/w numpy array and python sequences [list,string ,touple ,etc]

## What is a Python Sequence?
#### - An ordered collection of elements.
#### - Each element has an index (starts from 0).
#### - Can store multiple values.
#### - Supports indexing, slicing, iteration, and membership testing.
#### - Examples: String, List, Tuple, Range, Bytes, Bytearray.

# What is a NumPy Array?
#### - A NumPy array (ndarray) is a fast, efficient data structure for numerical data.
##### - Stores elements of the same data type.
#### - Supports multi-dimensional arrays (1D, 2D, 3D, ...).
#### - Optimized for mathematical and scientific computations.


#### 1. Array Creation Functions
- np.array()       -> Create an array from a list or tuple.
- np.zeros()       -> Create an array filled with zeros.
- np.ones()        -> Create an array filled with ones.
- np.empty()       -> Create an empty array.
- np.arange()      -> Create an array with evenly spaced values.
- np.linspace()    -> Create an array with evenly spaced values over an interval.
- np.eye()         -> Create an identity matrix.
- np.full()        -> Create an array filled with a specified value.

#### 2. Array Information Functions
- arr.ndim         -> Number of dimensions.
- arr.shape        -> Shape of the array.
- arr.size         -> Total number of elements.
- arr.dtype        -> Data type of the array.
- arr.itemsize     -> Size of each element in bytes.

#### 3. Array Conversion Functions
- astype()         -> Change the data type of an array.
- tolist()         -> Convert a NumPy array to a Python list.

#### 4. Array Reshaping Functions
- reshape()        -> Change the shape of an array.
- flatten()        -> Convert to a 1D array (copy).
- ravel()          -> Convert to a 1D array (view when possible).
- transpose()      -> Transpose an array.
- T                -> Shortcut for transpose.

#### 5. Joining and Splitting Functions
- concatenate()    -> Join arrays.
- stack()          -> Stack arrays along a new axis.
- hstack()         -> Stack horizontally.
- vstack()         -> Stack vertically.
- split()          -> Split an array.
- hsplit()         -> Split horizontally.
- vsplit()         -> Split vertically.

#### 6. Mathematical Functions
- add()            -> Addition.
- subtract()       -> Subtraction.
- multiply()       -> Multiplication.
- divide()         -> Division.
- power()          -> Raise to a power.
- sqrt()           -> Square root.
- abs()            -> Absolute value.

#### 7. Statistical Functions
- sum()            -> Sum of elements.
- mean()           -> Average.
- median()         -> Median.
- std()            -> Standard deviation.
- var()            -> Variance.
- min()            -> Minimum value.
- max()            -> Maximum value.
- argmin()         -> Index of the minimum value.
- argmax()         -> Index of the maximum value.

#### 8. Sorting Functions
- sort()           -> Sort an array.
- argsort()        -> Return indices that would sort the array.

#### 9. Searching Functions
- where()          -> Return indices where a condition is true.
- nonzero()        -> Return indices of non-zero elements.
- unique()         -> Return unique values.

#### 10. Linear Algebra Functions
- dot()            -> Dot product.
- matmul()         -> Matrix multiplication.
- linalg.inv()     -> Matrix inverse.
- linalg.det()     -> Determinant.
- linalg.eig()     -> Eigenvalues and eigenvectors.

#### 11. Random Functions
- random.rand()        -> Random numbers between 0 and 1.
- random.randint()     -> Random integers.
- random.randn()       -> Random numbers from a normal distribution.
- random.choice()      -> Randomly choose elements.
- random.shuffle()     -> Shuffle an array.

#### 12. Logical Functions
- all()            -> Check if all elements are True.
- any()            -> Check if any element is True.
- logical_and()    -> Logical AND.
- logical_or()     -> Logical OR.
- logical_not()    -> Logical NOT.

#### 13. File Functions
- save()           -> Save an array to a file.
- load()           -> Load an array from a file.
- savetxt()        -> Save as a text file.
- loadtxt()        -> Load from a text file.

# np.array()---> is used to create n dimentaionl array 


In [2]:
import numpy as np

In [3]:
numpy_array=np.array([1,2,3,4,5])

In [4]:
numpy_array

array([1, 2, 3, 4, 5])

In [5]:
type(numpy_array)

numpy.ndarray

In [6]:
two_dimential_array=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
two_dimential_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
three_dimentail_array=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [9]:
three_dimentail_array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

# dtype parameter --->which can store us out with deciding about the size of the data we are going to store inside our array

#### It tells NumPy what type of data should be stored in the array.
#### syntex:
#### np.array(object, dtype=data_type)

In [10]:
np.array([1,2,3,4],dtype=np.int32)
# this store the data in 32 bits

array([1, 2, 3, 4], dtype=int32)

In [11]:
np.array([1,2,3,4],dtype=np.int64)
# this store the data in 64 bits

array([1, 2, 3, 4])

In [12]:
#np.float32 and np.float64

In [13]:
np.array([11,12,13,14],dtype=int)

array([11, 12, 13, 14])

In [14]:
np.array([11,12,13,14],dtype=float)

array([11., 12., 13., 14.])

In [15]:
np.array([11,12,13,0],dtype=bool)

array([ True,  True,  True, False])

# range vs arange

In [16]:
#range
empty_list=[]
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


# arange:
#### it help us out with providing the values over certain range

In [17]:
# arange
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.arange(1,16,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

# reshpe()
#### The reshape() function is used to change the shape (dimensions) of a NumPy array without changing its data.

#### For example, you can convert:

##### A 1D array → 2D array
##### A 2D array → 3D array
##### Any shape → another compatible shape

In [20]:
arrange_data=np.arange(1,17)
arrange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
arrange_data=np.arange(1,17)
arrange_data.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

# ones()

#### The ones() function is used to create a NumPy array where every element is 1.
### syntax:
##### np.ones(shape, dtype=None)

In [22]:
np.ones((7))

array([1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# zeros():

#### The zeros() function is used to create a NumPy array where every element is 0.

#### syntex:
### np.zeros(shape, dtype=None)

In [24]:
np.zeros((4))

array([0., 0., 0., 0.])

In [25]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# random
#### The random module in NumPy is used to generate random numbers. It is commonly used in simulations, testing, Machine Learning, Deep Learning, and Generative AI.

#### Note: There is no function named np.random(). Instead, random is a module that contains many functions such as rand(), randint(), randn(), choice(), and shuffle().

### syntex:
#### np.random.function_name()

In [26]:
np.random.random((1,9))

array([[0.81291086, 0.80072626, 0.29585363, 0.74039202, 0.3736841 ,
        0.048259  , 0.49972037, 0.2624295 , 0.27865556]])

# identity():
#### it helps us out with creating the matrix as an identity matrix(square matrix--->row=column)

#### n identity matrix is a square matrix in which:

#### All diagonal elements are 1.
#### All other elements are 0.

In [27]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# linspace():

#### The linspace() function is used to create an array of evenly spaced numbers between a start value and an end value.

#### Unlike arange(), which uses a step size, linspace() uses the number of values you want.

### syntax:
#### np.linspace(start, stop, num=50, endpoint=True, dtype=None)

In [28]:
np.linspace(1,10,5,dtype=int)

array([ 1,  3,  5,  7, 10])

# attributes

#### ndim---->it tells the dimention of the array

In [29]:
arr=np.array([1,2,3,4])
arr.ndim

1

# shape:
#### it provides us with the idea about the row,column in out dataset or in our array

In [30]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

# size:
#### The size attribute is used to find the total number of elements in a NumPy array.


In [31]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
a.size

8

# itemsize
#### The itemsize attribute is used to find the memory size (in bytes) of one element in a NumPy array.

In [32]:
a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
a.itemsize

8

# dtype:
#### The dtype attribute in NumPy is used to find the data type of the elements stored in a NumPy array.

#### It tells you whether the array contains integers, floats, strings, booleans, etc.

In [33]:
arr = np.array([1.5, 2.5, 3.5])
arr.dtype

dtype('float64')

# astype()

#### The astype() function is used to change (convert) the data type (dtype) of a NumPy array.

#### It creates a new array with the specified data type.

In [34]:
arr=np.arange(1,10).reshape(3,3)
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

# mathemetical operation in numpy

## scaler operation ---> a scaler value operation  will be done with  the array or a numeric value (eg: 1 ,2,3 etc)

In [36]:
arr1=np.random.random((3,3))*100
arr1=np.round(arr1).astype('int32')
arr1


array([[82, 82,  4],
       [98, 16, 51],
       [27, 71, 17]], dtype=int32)

#### scaler opertaion with the matrix or array

In [37]:
arr1+2

array([[ 84,  84,   6],
       [100,  18,  53],
       [ 29,  73,  19]], dtype=int32)

In [38]:
arr1-5

array([[77, 77, -1],
       [93, 11, 46],
       [22, 66, 12]], dtype=int32)

In [39]:
arr1/2

array([[41. , 41. ,  2. ],
       [49. ,  8. , 25.5],
       [13.5, 35.5,  8.5]])

### we can apply scaler operation with the array in term of  arithematic operation 

In [40]:
a=5
b=6
b>a

True

In [41]:
arr1

array([[82, 82,  4],
       [98, 16, 51],
       [27, 71, 17]], dtype=int32)

In [42]:
arr1>60

array([[ True,  True, False],
       [ True, False, False],
       [False,  True, False]])

# vector operation
#### operation will be between the given no of matrices

In [43]:
arr_1=np.arange(1,17).reshape(4,4)
arr_2=np.arange(17,33).reshape(4,4)

In [44]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [45]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [46]:
arr_1+arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [47]:
arr_2-arr_1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [48]:
arr_1*arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

# important function in numpy for machine learing and data science

# max():
#### it is used for calculating the max value inside a matrix or array
#### syntax:
#### np.max(array)

In [49]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
max_value=np.max(arr_1)
max_value

np.int64(16)

# if we want to calculate the max or min value in any row or column

In [51]:
arr_data=np.random.random((4,4))*100
arr_data=arr_data.round().astype(int)


# axis:
#### it provide us with the idea about the any operation value inside a specific row or column or we can get a specific value row wise or column wise

#### axis=0 ----> column wise operation
#### axis=1 ----> row wise operation


In [52]:
arr_data

array([[20, 42, 24, 67],
       [69, 33, 66, 58],
       [29, 21,  9, 23],
       [90, 91, 99, 30]])

In [53]:
np.max(arr_data,axis=0)

array([90, 91, 99, 67])

In [54]:
np.max(arr_data,axis=1)

array([67, 69, 29, 99])

# min():
#### it is used for calculating the min value inside a matrix or array
#### syntax:
#### np.min(array)

# sum():
#### calculate the sum of all of the values of a given matrix
#### syntax:
##### np.sum(array)

In [55]:
arr_data

array([[20, 42, 24, 67],
       [69, 33, 66, 58],
       [29, 21,  9, 23],
       [90, 91, 99, 30]])

In [56]:
np.sum(arr_data)


np.int64(771)

## if i want to calculate the Sum of all values row or column wise

In [57]:
np.sum(arr_data,axis=0)

array([208, 187, 198, 178])

In [58]:
np.sum(arr_data,axis=1)

array([153, 226,  82, 310])

# prod():
#### product of all the values inside the matix or array

In [59]:
arr_data

array([[20, 42, 24, 67],
       [69, 33, 66, 58],
       [29, 21,  9, 23],
       [90, 91, 99, 30]])

In [60]:
np.prod(arr_data)

np.int64(-1821098111904353280)

In [61]:
np.prod(arr_data,axis=0)

array([3601800, 2648646, 1411344, 2681340])

# statistical function in numpy

# 1. mean(): 
#### mean of all values inside the array or matrix
#### syntax:
#### np.mean(array)



In [62]:
arr_data=np.random.random((4,4))*100
arr_data=arr_data.round().astype(int)


In [63]:
np.mean(arr_data)

np.float64(44.625)

In [64]:
np.mean(arr_data,axis=0)

array([40. , 58.5, 42. , 38. ])

In [65]:
np.mean(arr_data,axis=1)

array([61.5, 34. , 35. , 48. ])

# 2. std():standard devitation
#### it provide the stadrad deviation of given matix or array
#### syntex:
#### np.std(array)

In [66]:
arr_data

array([[47, 79, 65, 55],
       [80, 15, 36,  5],
       [30, 49, 26, 35],
       [ 3, 91, 41, 57]])

In [67]:
np.std(arr_data)

np.float64(25.255878028688688)

In [68]:
np.std(arr_data,axis=0)

array([27.91952722, 29.40663191, 14.33527119, 20.90454496])

In [69]:
np.std(arr_data,axis=1)

array([11.94780315, 28.8183969 ,  8.6890736 , 31.63858404])

# 3.medain():
#### it calculate the median of given matrix or array


In [70]:
arr_data

array([[47, 79, 65, 55],
       [80, 15, 36,  5],
       [30, 49, 26, 35],
       [ 3, 91, 41, 57]])

In [71]:
np.median(arr_data)

np.float64(44.0)

In [72]:
np.median(arr_data,axis=0)

array([38.5, 64. , 38.5, 45. ])

In [73]:
np.median(arr_data,axis=1)

array([60. , 25.5, 32.5, 49. ])

# 4.var():
#### calculate all values inside the all values inside the matix or array


In [74]:
np.var(arr_data)

np.float64(637.859375)

In [75]:
np.var(arr_data,axis=0)

array([779.5 , 864.75, 205.5 , 437.  ])

In [76]:
np.var(arr_data,axis=1)

array([ 142.75,  830.5 ,   75.5 , 1001.  ])

# trignometric functions

## 1.sin():
#### give the value of sin for given value inside it
#### syntex:
#### np.sin(value)

In [77]:
np.sin(90)

np.float64(0.8939966636005579)

In [78]:
np.tan(60)

np.float64(0.320040389379563)

In [79]:
np.cos(45)

np.float64(0.5253219888177297)

# dot product of matrices

syntax:

np.dot(matrix1,matrix2)

In [80]:
arr_1=np.round(np.random.random((3,4))*100).astype('int32')
arr_2=np.round(np.random.random((4,4))*100).astype('int32')

In [81]:
arr_1

array([[94,  4, 82, 79],
       [55, 66, 63, 70],
       [ 4, 56, 87, 86]], dtype=int32)

In [82]:
arr_2

array([[58, 98, 48, 11],
       [86, 54, 48, 10],
       [87, 94, 75, 55],
       [ 4, 37, 12,  2]], dtype=int32)

In [83]:
np.dot(arr_1,arr_2)

array([[13246, 20059, 11802,  5742],
       [14627, 17466, 11373,  4870],
       [12961, 14776, 10437,  5561]], dtype=int32)

# log():
#### to calculate the log of all the values of the matrix

In [84]:
np.log(arr_1)

array([[4.54329478, 1.38629436, 4.40671925, 4.36944785],
       [4.00733319, 4.18965474, 4.14313473, 4.24849524],
       [1.38629436, 4.02535169, 4.46590812, 4.4543473 ]])

# exp():
#### use to calculate the all values of the matrix

In [85]:
np.exp(arr_1)

array([[6.66317622e+40, 5.45981500e+01, 4.09399696e+35, 2.03828107e+34],
       [7.69478527e+23, 4.60718663e+28, 2.29378316e+27, 2.51543867e+30],
       [5.45981500e+01, 2.09165950e+24, 6.07603023e+37, 2.23524660e+37]])

# round():
#### use of this is to rounding off the float values to its nearest possible integer value
#### syntax:
#### np.round(value)

In [86]:
arrr=np.random.random((4,5))*100

In [87]:
arrr

array([[68.25739654, 76.08376855, 12.5317214 , 43.6729713 , 63.95551663],
       [81.97992485, 19.73596368, 45.22428404, 95.78383877, 16.05015421],
       [72.88837308, 60.14607788,  8.87795426, 13.11935775, 70.07240076],
       [ 2.63153411, 88.87743235, 73.35666676, 43.37970571, 65.99152683]])

In [88]:
np.round(arrr)

array([[68., 76., 13., 44., 64.],
       [82., 20., 45., 96., 16.],
       [73., 60.,  9., 13., 70.],
       [ 3., 89., 73., 43., 66.]])

# ceil()
#### it give just one greater value
#### syntax:
#### np.ceil(values)

In [89]:
arrr

array([[68.25739654, 76.08376855, 12.5317214 , 43.6729713 , 63.95551663],
       [81.97992485, 19.73596368, 45.22428404, 95.78383877, 16.05015421],
       [72.88837308, 60.14607788,  8.87795426, 13.11935775, 70.07240076],
       [ 2.63153411, 88.87743235, 73.35666676, 43.37970571, 65.99152683]])

In [90]:
np.ceil(arrr)

array([[69., 77., 13., 44., 64.],
       [82., 20., 46., 96., 17.],
       [73., 61.,  9., 14., 71.],
       [ 3., 89., 74., 44., 66.]])

# floor()
#### it give just smaller value
#### syntax:
#### np.floor(values)

# transpose():
#### use to calculate the tanspose of the given matrix
#### syntax:
np.tanspose(array) or array.T
tanspose---->(i,j) will be (j,i)

In [91]:
array=np.arange(1,13).reshape(3,4)

In [92]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# ravel():
 is used to convert a multi-dimensional array into a 1D (flattened) array.

 syntax:
 
 np.ravel(array)

In [94]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
np.ravel(array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# indexing and slicing in numpy

indexing ---->list[,size-1] ----> to have access over the valeus

In [96]:
array=np.round(np.random.random((5,5))*100).astype('int32')

In [97]:
array

array([[23, 49, 28,  5, 88],
       [11, 65, 56, 30, 42],
       [76, 71, 84,  6, 79],
       [ 7, 56,  5, 58, 32],
       [34, 39, 71, 54, 76]], dtype=int32)

In [98]:
array[0]

array([23, 49, 28,  5, 88], dtype=int32)

In [99]:
arr1=np.arange(1,10)

In [100]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
arr1[1]

np.int64(2)

for two dimential array

In [102]:
array[4,4]

np.int32(76)

# indexing for three D array

#### array[z axis,x axis,y axis]

In [103]:
three_dimentail_array=np.arange(1,9).reshape(2,2,2)

In [104]:
three_dimentail_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [105]:
three_dimentail_array[1,0,0]

np.int64(5)

In [106]:
three_dimentail_array[0,1,0]

np.int64(3)

# slicing

for one dimational 

similar approch just like the list[ : ]

2 D array ----->  [row_1:row_2 , col_1:col_2]

In [107]:
array

array([[23, 49, 28,  5, 88],
       [11, 65, 56, 30, 42],
       [76, 71, 84,  6, 79],
       [ 7, 56,  5, 58, 32],
       [34, 39, 71, 54, 76]], dtype=int32)

In [108]:
array[ : ,1]

array([49, 65, 71, 56, 39], dtype=int32)

In [109]:
array[1:4,0:1]

array([[11],
       [76],
       [ 7]], dtype=int32)

# iterating over the array

#### iteration happen row by row

In [110]:
array=np.arange(1,10)

In [111]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
for i in array:
    print(i)

1
2
3
4
5
6
7
8
9


In [113]:
array=np.arange(1,17).reshape(4,4)

In [114]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [115]:
for i in array: # this will print the array row by row first the first row then second and so on
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [116]:
array=np.arange(1,9).reshape(2,2,2)

In [117]:
array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [118]:
for i in array:
    print(i)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


# what if we want to iterate over values 

### nditer(array name):
    

In [119]:
array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [120]:
for i in np.nditer(array):
    print(i)

1
2
3
4
5
6
7
8


 -----------------------------------------------------
 ### 1 D ---->  value by value on iteration
 ### 2 D ---->  row by row on iteration
 ### 3d ------> 2D array by 2D array on iteration
 ------------------------------------------------------

# stacking and spliting in array

the size of the array should be same 

#### horizontal stacking: row by row joining ---->np.hstack()
#### vertical stacking: col by col joining ---->np.vstack()

In [121]:
arr1=np.arange(1,17).reshape(4,4)
arr2=np.arange(17,33).reshape(4,4)

In [122]:
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [123]:
total=np.hstack((arr1,arr2))

In [124]:
total

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [125]:
total=np.vstack((arr1,arr2))
total

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

# split funciton

#### horizontal split -----> hsplit(array,number of parts you want)
#### vertical split -----> vsplit(array,number of parts you want)


In [126]:
split_array=np.hsplit(total,2)
split_array

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22],
        [25, 26],
        [29, 30]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24],
        [27, 28],
        [31, 32]])]

In [127]:
split_array=np.vsplit(total,2)
split_array

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]